# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Read More
  description: Suggested resources from the library
  icon: wysiwyg
  tags:
    - Structure
    - Text
    - Links

# Defines the structure of this component, as well as the default values
blueprint:
  books: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  books: ""

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: 
  books:
    type: "text"
    comment: "it works"
    